site_name: RestAction
pages:
  - 首页: index.md
  - 起步: quickstart.md
  - resjs: resjs.md
  - Schema语法: schema.md
  - API: api.autodoc
theme: yeti
extra_css:
    - css/extra.css
markdown_extensions:
  - def_list
  - admonition
repo_url: 'https://github.com/guyskk/flask-restaction'
